### ISSUE TITLE
CLI: df

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#207]
- print a jails disk usage

**Comment by igalic** [comment]
this is the iocage implementation of `df`

```python
    def df(self):
        """Returns a list containing the resource usage of all jails"""
        jail_list = []

        for jail, path in self.jails.items():
            ds = self.zfs.get_dataset(mountpoint)
            zconf = ds.properties

            compressratio = zconf["compressratio"].value
            reservation = zconf["reservation"].value
            quota = zconf["quota"].value
            used = zconf["used"].value
            available = zconf["available"].value

            jail_list.append(
                [jail, compressratio, reservation, quota, used, available])

        return jail_list
```

(to simplify, i removed the special handling of templates)

**Comment by igalic** [comment]
there are a few ways someone could implement their own df, easily:

```sh
zfs list -r $(ioc get path tag=myjail)
```

or

```sh
df -h $(ioc get path tag=myjail)
```

or by running df directly in the jail:

```sh
ioc exec myjail df -h
```

the latter will even give you all listings that this particular jails has mounted via our `fstab` mechanism.

And it can also be used to run `top(1)` or other commands. Albeit, `top(1)`, and most *process* oriented commands have a `-J` switch, which allows us to slice out the jail in question anyway!

There are probably more interesting stats, that are harder to retrieve.
Instead of committing to backwards compatibility for such a simple command, we should probably consider stats streaming API

**Comment by gronke** [comment]
No code is best code 💛
