### ISSUE TITLE
Allow dataset from different pool in jail_zfs_dataset

### ISSUE THREAD

**Issue by skarekrow** [iocage/libiocage#23]
@rexpo opened this on https://github.com/iocage/iocage/issues/345
iocage is activated on one (for example small, SSD-backed) zpool, and I want to be able to mount datasets from a second (for example massive, but slow HDD-backed) zpool.

This isn't currently possible, as iocage can only mount a dataset from the same pool that iocage is activated on.

I know that I should just shut up, activate the big slow pool, throw lots of RAM at the host, and take comfort in the fact that the ZFS ARC will eventually speed things up. There are, however, other use cases that benefit from the ability to mount a dataset from another pool, especially when it comes to maintenance and migration.

As far as I can tell, work was done on iocage_legacy to implement just such a feature, but that it never made it to prime time. I'm sure this has already been discussed before, but I couldn't find any closed issues about it. Has this already been considered?

**Comment by gronke** [comment]
There is already a [setter to override a jail's dataset_name](https://github.com/iocage/libiocage/blob/eafdbf47a908ad138dcf41b45a0995222f00c1cc/libiocage/lib/Jail.py#L746) that point a jail to a specific dataset. 
It's used here when [executing release updates](https://github.com/iocage/libiocage/blob/eafdbf47a908ad138dcf41b45a0995222f00c1cc/libiocage/lib/Release.py#L324).

@rexpo, @skarekrow let's talk about a user interface. How would you expect to configure this as a user? Should iocage maintain multiple pools? If so, this feature would have a global impact. Not that it would be too complicated, but it's a larger effort that will require changes through the whole lib.

**Comment by rexpo** [comment]
I ran into this yesterday as I was testing migration of my ownCloud jail from my production host to my lab host.

As I came to the point where I was ready to attach my external dataset to the jail, my instinct was to set `jail_zfs_dataset=my-other-pool/owncloud-dataset` - I did it without even thinking; "of course I need to specify the pool", I thought.

***So my initial thought is to allow the user to specify the `zfs_filesystem` with or without specifying the pool. If the pool isn't specified, use the pool that iocage is activated on. Otherwise use the specified pool.***

A potential problem arises though, in the UI logic code needed to determine whether or not the user included the pool in their specification of `zfs_filesystem`. For example the case where they have done something silly like create a dataset on their jail pool with the same name as another pool on the system:

```
zpool create -O canmount=off -m none jailpool /dev/da1 /dev/da2
zpool create -m /mnt/tank tank /dev/da3 /dev/da4 /dev/da5 /dev/da6
iocage activate jailpool
...
zfs create -o mountpoint=none jailpool/tank
iocage set jail_zfs_dataset=tank/owncloud-data owncloud-testjail
```

As for whether iocage should manage these other pools, I hadn't thought of that. My initial reaction is 'no', but what about snapshots? What about jail export? Do we take care of them (has lib-wide consequences, as you say), or are external-pool datasets a "you're on your own!" kind of thing?

**Comment by skarekrow** [comment]
That's originally why I only allowed it on the same pool. I can see the benefits, but there are a lot of considerations if we do this lib-wide.

I would vote __no__ on allowing multiple pools usable by iocage. I think the complexity added to logic is a bigger issue than adding additional vdevs to a pool.

**Comment by rexpo** [comment]
In other words, you're saying no multiple pools altogether, not even unmanaged "you're on your own" ones?

(and in not so many words, you're agreeing with my "throw more RAM (and spindles) at my host" statement?)

**Comment by skarekrow** [comment]
No, I'm saying I don't agree with having multiple pools managed by iocage, I think we should stick to one.

I'm also not agreeing with your sentiment on throwing more RAM ;) I think if you want a _jailed dataset_ outside the managed iocage pool, it should be allowed. That's of little importance to iocage, and in the current implementation was mostly an oversight to how I did it in legacy. So that behavior should be available to users when we get back to this.

**Comment by rexpo** [comment]
Ah! cool :smiley: sounds great to me!

**Comment by gronke** [comment]
👍 to allow user-defined datasets for jails that are not "managed" by iocage. Can be neat to start a Jail from an USB stick or so.

I have a few scenarios in mind where multiple pools for iocage can be very nice to have. But the complexity this brings to iocage is something that blocks me at this stage to think about implementing it.

**Comment by gronke** [comment]
A first step towards this will be made with #72

**Comment by gronke** [comment]
In general this is now supported in libiocage. There is no way (planned yet) to use the feature from the CLI, but by using the Python library, you're free to point to any compatible resource (a dataset with a `root/` dataset inside).
