### ISSUE TITLE
IPv6 support might be broken

### ISSUE THREAD

**Issue by urosgruber** [iocage/libiocage#301]
While testing on a server with IPv6 iocage legacy jail latest `ioc` gives an error with invalid format for **ip6_addr** attribute

```
Invalid value for property 'ip6_addr' of jail 3789fbae: expected "<nic>|<address>" but got "20xx:xx:x:x::xx:xx"
```
I did update value with the expected format but then legacy `iocage start` output

```
jail: /sbin/ifconfig igb0 inet6 20xx:xx:x:x::xx:xx prefixlen 128 alias: failed
```

All this was tested on FreeBSD 10.x. I'm guessing legacy iocage is broken and my question is if theres is anything that can be done on `ioc` about this or should I patch legacy version myself?

**Comment by gronke** [comment]
libiocage is supposed to be compatible to iocage_legacy, so that even newly created jails can be managed with iocage_legacy. There will be a migration path to update jails to the latest standards (which is mostly what python-iocage does). @skarekrow told me that python-iocage is supposed to reach feature parity with iocage_legacy soon.

So whatever you find broken after using libiocage with older jails is definitely a bug!

I will try to reproduce this and let you know as soon as possible. Thanks for reporting this issue, @urosgruber 😄

**Comment by gronke** [comment]
@urosgruber the error you have posted above can be reproduced by setting only the IPv6 address, but not the interface:

```
$ ioc set ip6_addr="20xx:xx:x:x::xx:xx" 3789fbae
Invalid value for property 'ip6_addr' of jail 3789fbae: expected "<nic>|<address>" but got "20xx:xx:x:x::xx:xx"
```

Instead the command to set the IPv6 address should be:
```sh
ioc set ip6_addr="20xx:xx:x:x::xx:xx" 3789fbae
```

Issue #371 aims to improve variable parsing and error handling on set, which will make it easier to detect input mistakes.

**Comment by urosgruber** [comment]
So was this fixed on latest master? I have only ipv6 set on legacy iocage without interface.

**Comment by gronke** [comment]
The iocage-legacy [man page](https://www.freebsd.org/cgi/man.cgi?query=iocage&sektion=8) defines the variable content as `<nic>|<ipv6-address>`:

```
ip4_addr="interface|ip-address/netmask"
           The IPv4 address for VNET and shared IP jails.

ip6.addr, ip6.saddrsel, ip6
           A set of IPv6 options for the prison, the counterparts to
           ip4.addr, ip4.saddrsel and ip4 above.
```

Did I miss that feature? iocage would need to detect or guess your primary nic when just the IP is specified instead of nic|address pairs.
