### ISSUE TITLE
ioc start '*' failing when some jails already running

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#373]
currently `ioc start '*'` fails if some of the jails are already running.
conversely, `ioc stop '*'` fails if some of the jails are already stopped.

Should we continue this behaviour?
***specifically*** when the filter is `*`.

**Comment by gronke** [comment]
Personally I find is more consistent to always target the same jails in an operation. Pre-defining a `running=yes` filter changes the behavior from "Will apply the start operation on all matching jails" to "Will do some magic to enhance your input". Imagine we want to do the same with the set operation. Should it also only address stopped jails and not complain at all when a property wasn't set because the jail was never selected.

**Comment by igalic** [comment]
aye — thanks for the explanation
