### ISSUE TITLE
Allow to set base dataset other than iocage

### ISSUE THREAD

**Issue by urosgruber** [iocage/libiocage#53]
I think **iocage** dataset is what is currently hardcoded, right? It would be great if `iocage activate` would allow to specify base dataset other than **iocage**. This would allow easier migration from legacy jails. Right now only single dataset can exist and after installing new iocage old legacy jails will not properly start/stop. 

I created iocage_legacy port with renamed commands but I'm not sure how to get around this dataset naming clash.

**Comment by gronke** [comment]
With libiocage you are able to run mixed legacy jails and ones with newer config versions where you can start and stop your legacy jails. Even changes were applied to existing configuration, unless you wish to migrate.

At the current state migration is not implemented yet (but a low-hanging fruit) and I haven't manually the capability to start ioc legacy jails with the recent changes on libiocage.

I'm closing this issue because it's not planned to support other base datasets than `iocage` with the first version of libiocage. After the main CLI utilizes the library as well, we will discuss ways to maintain jails in multiple pools or base datasets. Whatever the solution will be, it will require to set custom iocage base datasets - but it's not required to support all kinds of legacy jails at the moment.

**Comment by gronke** [comment]
@urosgruber Thanks for mentioning it! Knowing there are other users that want this feature-set makes it a higher priority :) We'll mention in the README when manual tests for legacy jails were finished.

**Comment by urosgruber** [comment]
@gronke will there be support for legacy **master** version only? We're on develop because of some needed features and better performance. I might need to create a migration script that will handle all the differences. Right now I have about 250 jails running and growing daily.

**Comment by gronke** [comment]
@urosgruber I have implemented support for every configuration format I could find. So far this were:

- iocage-legacy (ZFS properties)
- iocage-legacy and iocage-python (UCL `config` file)
- iocage-python (JSON `config.json` file)

If you know about any other configuration format, I'd be happy about a sample and steps to create a jail with that format myself.

**Comment by urosgruber** [comment]
@gronke is this on some branch I can play with it? I think develop version is using UCL config file.

**Comment by gronke** [comment]
Yeah, maybe you want to verify it's working as expected by checking on the python cli. Please backup the Jail dataset with send/recv (recursive) before attempting to start a jail. Depending on your jail type it might write to fstab and/or rc.conf. Just to be careful!

```python
# cd libiocage/
# python3.6
>>> import libiocage
>>> jail = libiocage.Jail("<NAME_OR_UUID>"
>>> # print found configuration
>>> jail.config.data
>>> # Please BACKUP before starting
>>> jail.start()
```

**Comment by urosgruber** [comment]
@gronke can you help me with install of libiocage. Both pip and through git checkout gives me
```
 Could not find a version that satisfies the requirement libzfs (from libiocage==0.1.4) (from versions: )
No matching distribution found for libzfs (from libiocage==0.1.4)
```

**Comment by urosgruber** [comment]
@gronke I was able to get this running. After some testing config looks good, but there is an issue with start. Jail gets started but ioc start spits this out
```
Command exited with 1: /usr/sbin/jexec ioc-2a7ee61e-8c2d-11e7-b2a2-7071bca7c826 /bin/sh /etc/rc
    jexec: execvp: /bin/sh: No such file or directory
Command exited with 1
```

**Comment by gronke** [comment]
Looks like the jail is empty or contains an incomplete release.

@urosgruber do you want to join us on freenode #iocage ? @igalic and me fixed some problems with fetching recently and the PRs are almost merged. There's one larger refactoring upcoming, but you'll see in the PR notes 😼

**Comment by urosgruber** [comment]
@gronke latest pull on master and rebuild fixed this issue. I'll join on #iocage because I still have some questions.

**Comment by tommarcoen** [comment]
I would like this request to be opened again. I too want to install to a different dataset than `/iocage`. I prefer to have my data underneath `/var`, i.e. `/var/iocage`.

Is this request a hard no or can I submit a pull request once I get this working?

**Comment by gronke** [comment]
You can create the dataset manually and then enable it in for ioc:

```sh
zfs create -o mountpoint=/var/ioc zroot/storage/ioc
sysrc ioc_dataset_ioc="zroot/storage/ioc"
```

Dataset activation in /etc/rc.conf is preferred because it is faster than looking up all ZFS pools on the system. On one hand it also makes you more flexible to target any dataset, on the other it allows to use multiple datasets (and pools). For instance:

```sh
sysrc ioc_dataset_ioc="zroot/ioc"
sysrc ioc_dataset_secondary="tank/ioc"
```

Please feel free to reopen the issue if that did not solve your problem.
